name: Test Workflow Dispatch

on:
  workflow_dispatch:  # This is needed for manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Say Hello
        run: echo "Hello from GitHub Actions!"

